name: Continuous Integration

on:
  push:
    branches: [ master, test-workflows ]
  pull_request:
    branches: [ master, test-workflows ]

jobs:
  build:
    name: Test Workflows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: build-push
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.MY_DOCKER_USER }}
          password: ${{ secrets.MY_DOCKER_PASSWORD }}
          registry: ${{ secrets.MY_DOCKER_REGISTRY }}
          repository: ${{ secrets.MY_DOCKER_USER }}/docker-images/gotest
          tags: v1
          push: false
          path: "."
          dockerfile: build/Dockerfile
          tag_with_ref: true