name: Continuous Integration

on:
  push:
    branches: [ master, test-workflows ]
  pull_request:
    branches: [ master, test-workflows ]

jobs:

  build:
    name: Build Artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Build Image
        uses: docker/build-push-action@v1
        with:
          repository: ${{ secrets.MY_DOCKER_USER }}/docker-images/gotest
          tags: v1
          dockerfile: build/Dockerfile
          path: "."
          # username: ${{ secrets.MY_DOCKER_USER }}
          # password: ${{ secrets.MY_DOCKER_PASSWORD }}
          # registry: ${{ secrets.MY_DOCKER_REGISTRY }}
          tag_with_sha: true
          push: false

  publish:
    name: Publish Artifacts
    runs-on: ubuntu-latest
    needs: build
    if: github.event.pull_request.merged
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      # Push, replace v1 with the actual GIT_TAG
      - name: Push Image
        uses: docker/build-push-action@v1
        with:
          repository: ${{ secrets.MY_DOCKER_USER }}/docker-images/gotest
          tags: v1
          dockerfile: build/Dockerfile
          path: "."
          username: ${{ secrets.MY_DOCKER_USER }}
          password: ${{ secrets.MY_DOCKER_PASSWORD }}
          registry: ${{ secrets.MY_DOCKER_REGISTRY }}
          push: true