name: Continuous Integration

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master
  create:
    tags:
      - 'v[0-9].[0-9].[0-9]+*'

env:
  DOCKER_BUILDKIT: 1

jobs:

  build:
    name: Build Artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Unit Tests
        run: |
          go test ./...
          go version
      # - name: Build Image
      #   uses: docker/build-push-action@v1
      #   with:
      #     repository: ${{ secrets.MY_DOCKER_USER }}/docker-images/gotest
      #     dockerfile: build/Dockerfile
      #     path: '.'
      #     tag_with_sha: true
      #     push: false
      - name: Retrieve Tag
        id: get_version
        run: echo ::set-output name=GIT_TAG::$(echo ${GITHUB_REF/refs\/tags\//} | tr -d v)
      - name: NotifyIfFailed
        if: failure()
        run: echo Notification Here

  publish:
    name: Publish Artifacts
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'create' && contains(github.ref, 'refs/tags/')
    # if: github.event_name == 'create' && contains(github.ref, 'refs/tags/')
    # if: github.event.push.tags && contains(github.ref, 'release') # If working on a release branch
    # if: github.event.label.name == '<label_name>'                 # If particular label is set
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Retrieve Tag
        id: get_version
        run: echo ::set-output name=GIT_TAG::$(echo ${GITHUB_REF/refs\/tags\//} | tr -d v)
      - name: Push Image
        uses: docker/build-push-action@v1
        with:
          repository: ${{ secrets.MY_DOCKER_USER }}/docker-images/gotest
          dockerfile: build/Dockerfile
          path: '.'
          username: ${{ secrets.MY_DOCKER_USER }}
          password: ${{ secrets.MY_DOCKER_PASSWORD }}
          registry: ${{ secrets.MY_DOCKER_REGISTRY }}
          tag_with_ref: false
          tags: latest, ${{ steps.get_version.outputs.GIT_TAG }}
          push: true

  testJob:
    name: Always
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: TestJob
        run: echo "I always run!"

  # For slack notifications and stuff
  testJobFail:
    name: OnlyIfFailed
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - name: TestJobWhenFailed
        run: echo "Execute when something fails!"